// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileRead = { content: string, mtime_ms: bigint, encoding: string, };

export type FileWritten = { mtime_ms: bigint, };

export type FsError = { "kind": "NotFound", "detail": string } | { "kind": "PermissionDenied", "detail": string } | { "kind": "IsDirectory", "detail": string } | { "kind": "NotUtf8", "detail": string } | { "kind": "LooksBinary", "detail": string } | { "kind": "Io", "detail": string };

export type DirEntry = { name: string, path: string, is_dir: boolean, };

export type FileChanged = { path: string, mtime_ms: bigint, };
